title: Kirana Ananda - Researcher
logo:  # you can add own logo.
description: Insights seeker who continuously expanding knowledge in behavioral and market research. 
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Kirana Ananda
  image:  '/assets/img/kirana.jpg'
  job: Junior Research Executive
  bio: Insights seeker who continuously expanding knowledge in behavioral and market research. 
  email: kiranadwima@gmail.com


# Contact links
contact:
  - name: LinkedIn
    link: https://linkedin.com/in/kiranaananda
    image: '/assets/img/linkedin.png'


# Comment Section (Disqus)
disqus-identifier: Kirana # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
